### ISSUE TITLE
Enable assets to be bundled with NPM

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/maas-gui-vanilla-theme#45]
Currently npm doesn't pull in assets (fonts, images) as a part of the package. Look into adding an npm module which will manage this and publish any files required

**Comment by nottrobin** [comment]
@richmccartney Is this not a duplicate of https://github.com/ubuntudesign/maas-gui-vanilla-theme/issues/10 ?

@anthonydillon made the point:

> In Juju I grab that assets and place them into the image asset directory in the app. Then i change the asset-path to a local path.

Does this not solve your problem for some reason?

**Comment by richmccartney** [comment]
Closing issue as the user can just hot link fonts from google if required or use the bundled fonts in the framework.
