### ISSUE TITLE
Lacking notifications

### ISSUE THREAD

**Issue by roaksoax** [ubuntudesign/maas-gui-vanilla-theme#54]
Vanilla framework is lacking example for notifications.

https://github.com/CanonicalLtd/MAAS-design/tree/master/Notifications/Flat_Visuals/

**Comment by richmccartney** [comment]
@roaksoax this has now be released in the 1.1.0 release of the framework and can be seen on the documentation page http://ubuntudesign.github.io/maas-gui-vanilla-theme/
