### ISSUE TITLE
Missing icons?

### ISSUE THREAD

**Issue by ltrager** [ubuntudesign/maas-gui-vanilla-theme#64]
The [example page](http://ubuntudesign.github.io/maas-gui-vanilla-theme/index.html) lists the following icons however these icons are not shown on the example page nor are they usable in MAAS.

`<i class="icon icon--status-failed">..</i>`
`<i class="icon icon--status-in-progress">..</i>`
`<i class="icon icon--status-queued">..</i>`
`<i class="icon icon--status-succeeded">..</i>`
`<i class="icon icon--status-waiting">..</i>`

**Comment by kwm14** [comment]
@ltrager are you referring to the new icons seen in my latest designs for hardware testing?

**Comment by ltrager** [comment]
I believe those are the icons used in your design, I can't see the icon names but they look different. Regardless those icons should either be added or the listing removed.

**Comment by kwm14** [comment]
@richmccartney please find 'hardware testing' icons attached to add into GUI vanilla theme for Lee.

[hardware-testing-icons.zip](https://github.com/ubuntudesign/maas-gui-vanilla-theme/files/803523/hardware-testing-icons.zip)

**Comment by richmccartney** [comment]
http://ubuntudesign.github.io/maas-gui-vanilla-theme/index.html - at icons you can now see the new additions. @ltrager @kwm14 

@ltrager to update MAAS now needs to include v1.2.4 when building all npm modules.
